language: php
sudo: false
branches:
  except:
  - trunk
  - assets
  - "/^release-v.*$/"
matrix:
  include:
  - php: 5.6
    env: WP_VERSION=4.4 PHPLINT=1 PHPCS=1
cache:
  directories:
  - vendor
  - node_modules
  - "$HOME/.composer/cache"
before_script:
- phpenv local 5.6
- composer selfupdate --no-interaction
- composer install --no-interaction
- phpenv local --unset
- PLUGIN_SLUG=$(basename $(pwd))
- phpenv rehash
script:
- if [[ "$PHPLINT" == "1" ]]; then find -L . -path ./vendor -prune -o -name '*.php'
  -print0 | xargs -0 -n 1 -P 4 php -l; fi
- if [[ "$PHPCS" == "1" ]]; then composer run-script phpcs; fi
notifications:
  slack:
    secure: xhRdeZcRwIvVqcI/tn3Npm8N83SvPkjbpK1wY3x1epi854SGtCd6iZGjKjIZUQ7fl0XnUhjOg23b45ukYZSmm5ktn/hsdrFSzPlFRZo6RQomObq/TZA9Vq8uAL5WiCKz5g+BmWt3kVRiQZvpRMU0VdzmA42jNvWxvgle8g04klxgp3IduAMzo8MOL2ubpF9k8ebEZ/TdeqVb8onUrUdOBP+Xtbu/l7cVPKW4yRGHpikOMrwfL0OTGOhETcBsF6QiCLhifKCXtqXAc2vFRIg6j7/xOx8Kd9ZVkYPAGKbN56Omu8Ejw/RWVrKlC5WUoqjKS5DUQHuBBZw8rgm0PZkzOfEHRjwcQ8gLCROOqeL9LAq/YYNW2PgbOP9NWPyDij2rX5CI8ot24hKcHMpHWw1+uXZJ5S4piOo31DhBaMlju59h+Mrn0A2A6UfBMTmzQ/LBugkn4iINgWCU2QpplqV1plDc6alwP0PXRdHflKJr5kvGsLE2KjJfKlunmXQWeZKlFO/BwG7jAEuA/aJFX+LqRlug+PXU+CBuXc6XYDLgeSiG1TT6SOIpmK2MIBz4dbsxn1F7QyGXklsm7tw78tnHAmg7qIN9r8l3Ptl1Tlmx60zY4bKm1QUW0/VbblDu/pOc5KjEuFQ/UsBGW9XyUZ7LerKhq2/f7Fn/mjK5XewHKgA=
  email: false
